export const FETCH_REGION_START = 'FETCH_REGION_START';
export const FETCH_REGION__SUCCESS = 'FETCH_REGION__SUCCESS';
export const FETCH_REGION__FAILURE = 'FETCH_REGION__FAILURE';


export const ADD_REGION_START = 'ADD_REGION_START';
export const ADD_REGION__SUCCESS = 'ADD_REGION__SUCCESS';
export const ADD_REGION__FAILURE = 'ADD_REGION__FAILURE';

export const DEL_REGION_START = 'ADD_REGION_START';
export const DEL_REGION__SUCCESS = 'ADD_REGION__SUCCESS';
export const DEL_REGION__FAILURE = 'ADD_REGION__FAILURE';