# Generated by Django 3.1.4 on 2021-01-03 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_basic', '0004_auto_20210103_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('file_path', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_coulmn_name', models.CharField(max_length=255)),
                ('prevalue', models.CharField(max_length=255)),
                ('post_value', models.CharField(max_length=255)),
                ('modified_date', models.DateField()),
                ('section_id', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=150)),
                ('supplier_approver', models.CharField(max_length=150)),
                ('supplier_approval_date', models.DateField()),
                ('supplier_approval_status', models.CharField(max_length=255)),
                ('supplier_comment', models.CharField(max_length=255)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfApprovalChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_approver', models.CharField(max_length=150)),
                ('contract_approver_status', models.CharField(max_length=255)),
                ('contract_approver_comment', models.CharField(max_length=255)),
                ('FAT1_required', models.BooleanField(default=True)),
                ('FAT1_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT1_comments', models.CharField(max_length=255)),
                ('FAT2_required', models.BooleanField(default=True)),
                ('FAT2_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT2_comments', models.CharField(max_length=255)),
                ('FAT3_required', models.BooleanField(default=True)),
                ('FAT3_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT3_comments', models.CharField(max_length=255)),
                ('FAT1_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat1_hoc_rev', to=settings.AUTH_USER_MODEL)),
                ('FAT2_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat2_hoc_rev', to=settings.AUTH_USER_MODEL)),
                ('FAT3_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat3_hoc_rev', to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic')),
            ],
        ),
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_signature', models.ImageField(upload_to='media/images')),
                ('buyer_signed_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_signature', models.ImageField(upload_to='media/images')),
                ('supplier_signed_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('signed', 'signed'), ('not_signed', 'not signed')], default='pending', max_length=55)),
                ('supplier_comments', models.CharField(max_length=255)),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic')),
            ],
        ),
        migrations.CreateModel(
            name='ContractApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_approver', models.CharField(max_length=255)),
                ('contract_approver_comments', models.CharField(max_length=255)),
                ('contract_approver_status', models.CharField(max_length=255)),
                ('FAT1_required', models.BooleanField(default=True)),
                ('FAT1_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT1_comments', models.CharField(max_length=255)),
                ('FAT2_required', models.BooleanField(default=True)),
                ('FAT2_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT2_comments', models.CharField(max_length=255)),
                ('FAT3_required', models.BooleanField(default=True)),
                ('FAT3_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=55)),
                ('FAT3_comments', models.CharField(max_length=255)),
                ('FAT1_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat1_rev', to=settings.AUTH_USER_MODEL)),
                ('FAT2_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat2_rev', to=settings.AUTH_USER_MODEL)),
                ('FAT3_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat3_rev', to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic')),
            ],
        ),
    ]
