# Generated by Django 3.1.5 on 2021-01-19 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor_management', '0002_auto_20210119_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbasic',
            name='company_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbasic',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_rev', to=settings.AUTH_USER_MODEL),
        ),
    ]
