# Generated by Django 3.1.5 on 2021-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_auto_20210119_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbasic',
            name='supplier_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorbasic',
            name='supplier_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
