# Generated by Django 3.1.5 on 2021-01-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0004_auto_20210120_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbasic',
            old_name='supplier_city',
            new_name='supp_city',
        ),
        migrations.RenameField(
            model_name='vendorbasic',
            old_name='supplier_name',
            new_name='supp_name',
        ),
    ]
