# Generated by Django 3.1.5 on 2021-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0005_auto_20210120_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbasic',
            name='abn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
