# Generated by Django 3.1.5 on 2021-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0006_auto_20210120_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_tagname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_trade', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vendorbasic',
            name='tags',
            field=models.ManyToManyField(to='vendor_management.VendorTag'),
        ),
        migrations.AddField(
            model_name='vendorbasic',
            name='trade',
            field=models.ManyToManyField(to='vendor_management.VendorTrade'),
        ),
    ]
