# Generated by Django 3.1.5 on 2021-01-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0007_auto_20210124_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendortag',
            old_name='vendor_tagname',
            new_name='vendortagname',
        ),
        migrations.RenameField(
            model_name='vendortrade',
            old_name='vendor_trade',
            new_name='vendortrade',
        ),
    ]
