# Generated by Django 3.1.5 on 2021-01-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0008_auto_20210124_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbasic',
            options={'ordering': ['-id']},
        ),
    ]
