import checkoutFormModel from './checkoutFormModel';
const {
    formField: {
        supplier_name,
        supplier_type,
        supplier_contact_name,
        supplier_contact_phone,
        supplier_contact_email,
        supplier_ABN_number,
        panel_ranking,
        managed_as_panel_contractor,
        supplier_street_address,
        supplier_city,
        supplier_state,
        supplier_post_code,
        supplier_post_name,
        supplier_country,
        buyer_name,
        buyer_contact_name,
        buyer_contact_phone,
        buyer_contact_email,
        buyer_street_address,
        buyer_post_code,
        buyer_post_name,
        buyer_city,
        buyer_state,
        buyer_country,
        buyer_ABN_number,
        contract_title,
        contract_risk,
        contract_type,
        contract_manager,
        contract_initiator,
        contract_value,
        administrator,
        business_representative,
        purchase_type,
        contract_items,
        contract_owner,
        date_signed,
        review_date,
        price_review_date,
        contract_expiry,
        commencement_date,
        contract_insurance_req,
        ongoing,
        initial_term,
        contract_rates,
        department,
        business_unit,
        divisions,
        regions,
        category1,
        category2,
        category3,
        site,
    }
} = checkoutFormModel;





export default {
    [supplier_name.name]: '',
    [supplier_type.name]: '',
    [supplier_contact_name.name]: '',
    [supplier_contact_phone.name]: '',
    [supplier_contact_email.name]: '',
    [supplier_ABN_number.name]: '',
    [panel_ranking.name]: '',
    [managed_as_panel_contractor.name]: false,
    [supplier_street_address.name]: '',
    [supplier_city.name]: '',
    [supplier_state.name]: '',
    [supplier_post_code.name]: '',
    [supplier_post_name.name]: '',
    [supplier_country.name]: '',
    [buyer_name.name]: '',
    [buyer_contact_name.name]: '',
    [buyer_contact_phone.name]: '',
    [buyer_contact_email.name]: '',
    [buyer_street_address.name]: '',
    [buyer_post_code.name]: '',
    [buyer_post_name.name]: '',
    [buyer_city.name]: '',
    [buyer_state.name]: '',
    [buyer_country.name]: '',
    [buyer_ABN_number.name]: '',
    [contract_title.name]: '',
    [contract_risk.name]: '',
    [contract_type.name]: '',
    [contract_manager.name]: '',
    [contract_initiator.name]: '',
    [contract_value.name]: '',
    [administrator.name]: '',
    [business_representative.name]: '',
    [purchase_type.name]: '',
    [contract_items.name]: '',
    [contract_owner.name]: '',
    [date_signed.name]: '',
    [review_date.name]: '',
    [price_review_date.name]: '',
    [contract_expiry.name]: '',
    [price_review_date.name]: '',
    [commencement_date.name]: '',
    [contract_insurance_req.name]: false,
    [ongoing.name]: false,
    [initial_term.name]: '',
    [contract_rates.name]: '',
    [department.name]: [],
    [business_unit.name]: [],
    [divisions.name]: [],
    [regions.name]: [],
    [category1.name]: [],
    [category2.name]: [],
    [category3.name]: [],
    [site.name]: [],

};