# Generated by Django 3.1.4 on 2021-01-02 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContracttSectionAndClauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('clause_text', models.TextField()),
                ('contract_clause_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_clause_last_modified', models.DateTimeField(blank=True, null=True)),
                ('legal_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('legally_reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_status', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSectionAndClauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=255)),
                ('clause_text', models.TextField()),
                ('clause_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clause_last_modified', models.DateTimeField(blank=True, null=True)),
                ('clause_type', models.CharField(choices=[('default', 'default'), ('customized', 'customized')], default='default', max_length=55)),
            ],
        ),
    ]
