# Generated by Django 3.1.4 on 2021-01-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section_and_clauses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_basic', '0002_auto_20210102_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsectionandclauses',
            name='clause_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_creator_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultsectionandclauses',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttsectionandclauses',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_basic.contractbasic'),
        ),
        migrations.AddField(
            model_name='contracttsectionandclauses',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
