# Generated by Django 3.1.4 on 2021-01-03 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('section_and_clauses', '0002_auto_20210102_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttsectionandclauses',
            name='contract_clause_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contracttsectionandclauses',
            name='contract_clause_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultsectionandclauses',
            name='clause_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='defaultsectionandclauses',
            name='clause_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
