# Generated by Django 3.1.4 on 2021-01-03 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_basic', '0004_auto_20210103_0656'),
        ('section_and_clauses', '0003_auto_20210103_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContracttSectionAndClauses',
            new_name='ContractSectionAndClauses',
        ),
    ]
