# Generated by Django 3.1.5 on 2021-01-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_street_address', models.TextField()),
                ('buyer_post_code', models.CharField(max_length=50)),
                ('buyer_post_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_city', models.CharField(max_length=80)),
                ('buyer_state', models.CharField(max_length=80)),
                ('buyer_country', models.CharField(max_length=80)),
                ('buyer_ABN_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyercreator_rev', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_modifier_rev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
