export const FETCH_DEPT_START = 'FETCH_DEPT_START';
export const FETCH_DEPT_SUCCESS = 'FETCH_DEPT_SUCCESS';
export const FETCH_DEPT_FAILURE = 'FETCH_DEPT_FAILURE';


export const ADD_DEPT_START = 'ADD_DEPT_START';
export const ADD_DEPT_SUCCESS = 'ADD_DEPT_SUCCESS';
export const ADD_DEPT_FAILURE = 'ADD_DEPT_FAILURE';

export const DEL_DEPT_START = 'DEL_DEPT_START';
export const DEL_DEPT_SUCCESS = 'DEL_DEPT_SUCCESS';
export const DEL_DEPT_FAILURE = 'DEL_DEPT_FAILURE';