export const FETCH_TAGS_START = 'FETCH_TAGS_START';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';


export const ADD_TAGS_START = 'ADD_TAGS_START';
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAILURE = 'ADD_TAGS_FAILURE';

export const DEL_TAGS_START = 'DEL_TAGS_START';
export const DEL_TAGS_SUCCESS = 'DEL_TAGS_SUCCESS';
export const DEL_TAGS_FAILURE = 'DEL_TAGS_FAILURE';