export const FETCH_SITES_START = 'FETCH_SITES_START';
export const FETCH_SITES_SUCCESS = 'FETCH_SITES_SUCCESS';
export const FETCH_SITES_FAILURE = 'FETCH_SITES_FAILURE';


export const ADD_SITES_START = 'ADD_SITES_START';
export const ADD_SITES_SUCCESS = 'ADD_SITES_SUCCESS';
export const ADD_SITES_FAILURE = 'ADD_SITES_FAILURE';

export const DEL_SITES_START = 'DEL_SITES_START';
export const DEL_SITES_SUCCESS = 'DEL_SITES_SUCCESS';
export const DEL_SITES_FAILURE = 'DEL_SITES_FAILURE';