# Generated by Django 3.1.4 on 2021-01-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_basic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractbasic',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='contract_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modify_rev', to=settings.AUTH_USER_MODEL),
        ),
    ]
