# Generated by Django 3.1.4 on 2021-01-03 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract_basic', '0003_auto_20210103_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractbasic',
            name='commencement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='contract_expiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='date_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='price_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='contract_insurance_expiry',
            field=models.DateField(),
        ),
    ]
