# Generated by Django 3.1.5 on 2021-01-16 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract_basic', '0004_auto_20210103_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractbasic',
            name='business_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='category1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='category2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='category3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='contract_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='divisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_rev', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='regions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractbasic',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
