# Generated by Django 3.1.5 on 2021-01-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_basic', '0005_auto_20210116_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='divisions',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='contractbasic',
            name='site',
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='tags',
            field=models.ManyToManyField(to='contract_basic.Tags'),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='business_unit',
            field=models.ManyToManyField(to='contract_basic.BusinessUnit'),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='department',
            field=models.ManyToManyField(to='contract_basic.Department'),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='divisions',
            field=models.ManyToManyField(to='contract_basic.Divisions'),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='regions',
            field=models.ManyToManyField(to='contract_basic.Regions'),
        ),
        migrations.AddField(
            model_name='contractbasic',
            name='site',
            field=models.ManyToManyField(to='contract_basic.Sites'),
        ),
    ]
