# Generated by Django 3.1.5 on 2021-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_basic', '0006_auto_20210119_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='depname',
            new_name='bussname',
        ),
    ]
